### ISSUE TITLE
Is it a bug about la_tracker.ev?

### ISSUE THREAD

**Issue by grtzsohalf** [automl/RobustDARTS#2]
Hi, I found something weird in src/search/train_search.

In line 161, if args.compute_hessian, ev is assigned -1.
But i think it should be
```
if not args.compute_hessian:
    ev = -1
else:
    ev = la_tracker.ev[-1]
```
because la_tracker.ev is only appended something in line 421 when args.compute_hessian is True.
If I directly run your code, a list index out of range error occurs.

I am not sure if I understand it right.
Thank you!

**Comment by arberzela** [comment]
Hi,

Thanks a lot for looking into our code in details. That indeed is a bug. Sorry about that, I had forgotten to push the last changes. I just did that now.

Cheers,
Arber

**Comment by arberzela** [comment]
Fixed small bug in ```train_search.py```. See ```commit d8dc5de904420fcc825ee59567c43db21f2ae3e3```

**Comment by arberzela** [comment]
Fixed small bug in ```train_search.py```. See ```commit d8dc5de904420fcc825ee59567c43db21f2ae3e3```
