### ISSUE TITLE
Cutout variable

### ISSUE THREAD

**Issue by bolianchen** [automl/RobustDARTS#3]
Hi 

In train_search.py, there seems an intention to be strengthening the data augmentation along with the architecture search progress by increasing the probability to activate Cutout. 
 
      if args.drop_path_prob != 0:
        model.drop_path_prob = args.drop_path_prob * epoch / (args.epochs - 1)
        train_transform.transforms[-1].cutout_prob = args.cutout_prob * epoch / (args.epochs - 1)

However, the variable in Cutout is prob rather than cutout_prob; therefore, it looks like Cutout is always activated if args.cutout is set as True. Should the code be revised? Thanks.

      class Cutout(object):
        def __init__(self, length, prob=1.0):
        self.length = length
        self.prob = prob

**Comment by arberzela** [comment]
Hi,

the cutout probability is always increased linearly throughout epochs from 0 to ```args.cutout_prob```. Please check [this line of code](https://github.com/automl/RobustDARTS/blob/master/src/utils.py#L316).

Best,
Arber

**Comment by bolianchen** [comment]
Hi @arberzela 

The line you mentioned is to set up the whole data pre-processing pipeline (transforms) according to the initial parameters in args. It would not be used to update the cutout_prob in the pipeline.

    def _data_transforms_cifar10(args):
        ...
        if args.cutout:
            train_transform.transforms.append(Cutout(args.cutout_length,
                                          args.cutout_prob))


It seems you intend to dynamically update the cutout_prob with [this line](https://github.com/automl/RobustDARTS/blob/c850572f8153ced71d61e0493d614ac483a2c186/src/search/train_search.py#L113). It seems not working because the code try to update the self.cutout_prob variable for Cutout which actually uses self.prob to do its job.
