### ISSUE TITLE
question about analyser.compute_dw

### ISSUE THREAD

**Issue by bolianchen** [automl/RobustDARTS#4]
Hi,

Noticed you are monitoring 1st-order derivatives of loss versus architecture parameters as well when compute_hessian is activated. Is it to make sure the 1st-order derivatives are actually close to zero so the eigenvalues of hessian would be the global curvatures?

If so, what's the mechanism do you apply to judge if 1st-order derivatives are close to zero? Thanks very much!

Best,
Bolian

**Comment by arberzela** [comment]
Hi Bolian,

For that I am taking the norm of the gradient vector, but due to the high noise coming from the mini-batch computation we could not draw any conclusions from that.

Best,
Arber
